resource "random_id" "bucket_name" {
  byte_length = 4
}

/* since bucket names are global across accounts, generate a unique one */
resource "aws_s3_bucket" "log_bucket" {
  bucket        = "${lower("${var.base_name}-weblogs-${random_id.bucket_name.hex}")}"
  acl           = "private"
  force_destroy = "true"

  tags {
    Description = "Holds transaction logs generated by a NetScaler"
  }
}

output "log_bucket" {
   value = "${aws_s3_bucket.log_bucket.bucket}"
}
